/**
 *
 */
package com.rf.portal.catalogclient;

// TODO: This is the BONUS exercise. First complete the steps in StockWebServiceClient.java

// TODO: import all classes in the package generated from the CatalogService
//       by wsimport


/**
 *
 * Client application for catalog service
 *
 * @author Mike Woinoski
 *
 */
public class CatalogServiceClient {

    public static void main(String[] args) throws Exception {
        // TODO: Use the generated code to create a service factory for
        //       the web service proxy
        // HINT: look in the generated folder to find the name of the factory class
        //       that was generated by wsimport
        // HINT: add an import for the factory class



        // TODO: Use the service factory to create a web service proxy
        // HINT: Which method in the service factory should you call?
        // HINT: add an import for the proxy class



        // TODO: Use the web service proxy to send a request to the web service
        //       to find the catalog item with product id 3000



        // TODO: Print the item's product ID, title, artist, and price


    }

}
